package ngwafworkspacerule

import (
	"github.com/fastly/terraform-provider-fastly/internal/resources/ngwafrule"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ruleTypes are the rule `type` values valid for a workspace-scoped rule.
var ruleTypes = []string{"request", "signal", "rate_limit", "templated_signal"}

// actionTypes is the always-valid superset across all rule types;
// ValidateConfig enforces the precise per-rule-type set (see validate.go).
// templated_signal is the only action name that collides with a rule
// type value.
var actionTypes = []string{
	"allow", "block", "add_signal", "browser_challenge", "verify_token",
	"dynamic_challenge", "deception", "exclude_signal", "log_request", "block_signal",
	"templated_signal",
}

// deceptionTypes are the valid values for an action's deception_type,
// required when action.type = "deception".
var deceptionTypes = []string{"invalid_login_response", "vulnerable_application_response", "ato"}

var (
	groupOperators        = []string{"any", "all"}
	requestLoggingValues  = []string{"sampled", "none"}
	rateLimitIntervals    = []int64{60, 600, 3600}
	clientIdentifierTypes = []string{"ip", "post_parameter", "request_cookie", "request_header", "signal_payload"}
)

// DefaultGroupOperator is the value the API assigns to group_operator when
// it's omitted from the request body. request_logging has no equivalent
// constant: it's only meaningful on `request`-type rules, so it can't have
// one unconditional default (see the request_logging attribute below).
const DefaultGroupOperator = "all"

// Model is the top-level fastly_ngwaf_workspace_rule resource state.
type Model struct {
	ID                types.String                       `tfsdk:"id"`
	WorkspaceID       types.String                       `tfsdk:"workspace_id"`
	Type              types.String                       `tfsdk:"type"`
	Description       types.String                       `tfsdk:"description"`
	Enabled           types.Bool                         `tfsdk:"enabled"`
	GroupOperator     types.String                       `tfsdk:"group_operator"`
	RequestLogging    types.String                       `tfsdk:"request_logging"`
	Condition         []ngwafrule.ConditionModel         `tfsdk:"condition"`
	GroupCondition    []ngwafrule.GroupConditionModel    `tfsdk:"group_condition"`
	MultivalCondition []ngwafrule.MultivalConditionModel `tfsdk:"multival_condition"`
	Action            []ActionModel                      `tfsdk:"action"`
	RateLimit         []RateLimitModel                   `tfsdk:"rate_limit"`
}

// ActionModel is one action to take when the rule's conditions match.
type ActionModel struct {
	Type             types.String `tfsdk:"type"`
	Signal           types.String `tfsdk:"signal"`
	AllowInteractive types.Bool   `tfsdk:"allow_interactive"`
	DeceptionType    types.String `tfsdk:"deception_type"`
	RedirectURL      types.String `tfsdk:"redirect_url"`
	ResponseCode     types.Int64  `tfsdk:"response_code"`
}

// RateLimitModel configures a rate_limit-type rule's threshold and window.
type RateLimitModel struct {
	ClientIdentifiers []ClientIdentifierModel `tfsdk:"client_identifiers"`
	Duration          types.Int64             `tfsdk:"duration"`
	Interval          types.Int64             `tfsdk:"interval"`
	Signal            types.String            `tfsdk:"signal"`
	Threshold         types.Int64             `tfsdk:"threshold"`
}

// ClientIdentifierModel names one attribute of the request used to group
// requests for rate limiting.
type ClientIdentifierModel struct {
	Key    types.String `tfsdk:"key"`
	Name   types.String `tfsdk:"name"`
	Signal types.String `tfsdk:"signal"`
	Type   types.String `tfsdk:"type"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The rule identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		// workspace_id forces replacement: it's a path segment
		// (/ngwaf/v1/workspaces/{workspace_id}/rules/{rule_id}), not a request
		// body field, so there's no API call that moves an existing rule to a
		// different workspace - an in-place update would PATCH a rule ID that
		// doesn't exist under the new workspace's path and fail.
		"workspace_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the workspace this rule belongs to.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		// type is intentionally not ForceNew: the API's rule PATCH body
		// accepts a `type` field, so switching e.g. request -> signal via
		// Update is real, API-supported behavior this resource preserves
		// rather than second-guesses.
		"type": schema.StringAttribute{
			Required:    true,
			Description: "The type of the rule. One of `request`, `signal`, `rate_limit`, or `templated_signal`.",
			Validators: []validator.String{
				stringvalidator.OneOf(ruleTypes...),
			},
		},
		"description": schema.StringAttribute{
			Required:    true,
			Description: "The description of the rule. Must be an empty string for `templated_signal` rules.",
		},
		"enabled": schema.BoolAttribute{
			Required:    true,
			Description: "Whether the rule is currently enabled.",
		},
		"group_operator": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString(DefaultGroupOperator),
			Description: "Logical operator applied across the rule's top-level condition, group_condition, and multival_condition entries. One of `any` or `all`. Defaults to `all`.",
			Validators: []validator.String{
				stringvalidator.OneOf(groupOperators...),
			},
		},
		"request_logging": schema.StringAttribute{
			Optional: true,
			Computed: true,
			// No static Default: the API rejects request_logging on every
			// rule type but request, so defaulting it unconditionally would
			// fail elsewhere. Computed alone satisfies the consistency
			// check since the API returns "sampled" when unset on a
			// request rule.
			Description: "Logging behavior for matching requests. Only valid for `request`-type rules. One of `sampled` or `none`. Defaults to `sampled` when set on a `request` rule.",
			Validators: []validator.String{
				stringvalidator.OneOf(requestLoggingValues...),
			},
		},
	}
}

func ActionBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "List of actions to perform when the rule matches. At least one is required.",
		Validators: []validator.List{
			listvalidator.SizeAtLeast(1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"type": schema.StringAttribute{
					Required: true,
					Description: "The action type. Valid values depend on the rule's `type`: " +
						"`request` rules allow `allow`, `block`, `add_signal`, `browser_challenge`, `verify_token`, `dynamic_challenge`, or `deception` (1-2 actions); " +
						"`signal` rules require exactly `exclude_signal`; " +
						"`rate_limit` rules allow exactly one of `block_signal`, `log_request`, `browser_challenge`, `dynamic_challenge`, or `deception`; " +
						"`templated_signal` rules require exactly `templated_signal`.",
					Validators: []validator.String{
						stringvalidator.OneOf(actionTypes...),
					},
				},
				"signal": schema.StringAttribute{
					Optional:    true,
					Description: "Signal name. Required by `add_signal`, `exclude_signal`, `block_signal`, `log_request`, and `templated_signal`; optional on `browser_challenge`, `dynamic_challenge`, and `deception`.",
				},
				"allow_interactive": schema.BoolAttribute{
					Optional:    true,
					Description: "Specifies if interaction is allowed. Required when `type = browser_challenge`.",
				},
				"deception_type": schema.StringAttribute{
					Optional:    true,
					Description: "Specifies the type of deception. Required when `type = deception`. One of `invalid_login_response`, `vulnerable_application_response`, or `ato`.",
					Validators: []validator.String{
						stringvalidator.OneOf(deceptionTypes...),
					},
				},
				"redirect_url": schema.StringAttribute{
					Optional:    true,
					Description: "Redirect target. Optional companion to `type = block` or `type = block_signal`.",
				},
				"response_code": schema.Int64Attribute{
					Optional:    true,
					Description: "Response code used with `type = block` or `type = block_signal`.",
				},
			},
		},
	}
}

func RateLimitBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Configuration specific to `rate_limit`-type rules.",
		Validators: []validator.List{
			listvalidator.SizeAtMost(1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"duration": schema.Int64Attribute{
					Required:    true,
					Description: "Duration in seconds for the rate limit. Minimum `300`, maximum `86400`.",
					Validators: []validator.Int64{
						int64validator.Between(300, 86400),
					},
				},
				"interval": schema.Int64Attribute{
					Required:    true,
					Description: "Time interval for the rate limit in seconds. One of `60`, `600`, or `3600`.",
					Validators: []validator.Int64{
						int64validator.OneOf(rateLimitIntervals...),
					},
				},
				"signal": schema.StringAttribute{
					Required:    true,
					Description: "Reference ID of the custom signal this rule uses to count requests.",
				},
				"threshold": schema.Int64Attribute{
					Required:    true,
					Description: "Rate limit threshold. Minimum `1`, maximum `100000`.",
					Validators: []validator.Int64{
						int64validator.Between(1, 100000),
					},
				},
			},
			Blocks: map[string]schema.Block{
				"client_identifiers": ClientIdentifiersBlock(),
			},
		},
	}
}

func ClientIdentifiersBlock() schema.SetNestedBlock {
	return schema.SetNestedBlock{
		Description: "List of client identifiers used for rate limiting. Must contain 1 or 2 entries.",
		Validators: []validator.Set{
			setvalidator.SizeBetween(1, 2),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"key": schema.StringAttribute{
					Optional:    true,
					Description: "Key for the Client Identifier. Only valid when `type` is `request_header`; excluded otherwise.",
				},
				"name": schema.StringAttribute{
					Optional:    true,
					Description: "Name for the Client Identifier. Required when `type` is `request_header`, `request_cookie`, or `post_parameter`; excluded when `type` is `ip` or `signal_payload`.",
				},
				"signal": schema.StringAttribute{
					Optional:    true,
					Description: "Signal for the Client Identifier. Required when `type` is `signal_payload`; excluded otherwise.",
				},
				"type": schema.StringAttribute{
					Required:    true,
					Description: "Type of the Client Identifier. One of `ip`, `post_parameter`, `request_cookie`, `request_header`, or `signal_payload`.",
					Validators: []validator.String{
						stringvalidator.OneOf(clientIdentifierTypes...),
					},
				},
			},
		},
	}
}
