package ngwafworkspacesignal

import (
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var signalNamePattern = regexp.MustCompile(`^[a-zA-Z0-9\- ]+$`)

type Model struct {
	ID          types.String `tfsdk:"id"`
	WorkspaceID types.String `tfsdk:"workspace_id"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	ReferenceID types.String `tfsdk:"reference_id"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The workspace signal identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"workspace_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the workspace that owns the signal.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: "The name of the signal. Must be between 3 and 128 characters and contain only letters, numbers, spaces, and hyphens. The name is immutable after creation.",
			Validators: []validator.String{
				stringvalidator.LengthBetween(3, 128),
				stringvalidator.RegexMatches(signalNamePattern, "must contain only letters, numbers, spaces, and hyphens"),
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "The description of the signal. Maximum length is 140 characters.",
			Validators: []validator.String{
				stringvalidator.LengthAtMost(140),
			},
		},
		"reference_id": schema.StringAttribute{
			Computed:    true,
			Description: "The generated reference ID of the signal, for example `site.foo-signal`.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
	}
}
