package ngwaflist

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Attributes returns the schema shared by all type-specific workspace list resources.
func Attributes(listType string) map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The workspace list identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"workspace_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the workspace that owns the list.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: fmt.Sprintf("The name of the %s list. Must be between 3 and 32 characters. The name is immutable after creation.", listType),
			Validators: []validator.String{
				stringvalidator.LengthBetween(3, 32),
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "The description of the list. When set, must be between 3 and 140 characters.",
			Validators: []validator.String{
				stringvalidator.LengthBetween(3, 140),
			},
		},
		"entries": schema.ListAttribute{
			Required:    true,
			ElementType: types.StringType,
			Description: fmt.Sprintf("The entries in the %s list.", listType),
		},
		"reference_id": schema.StringAttribute{
			Computed:    true,
			Description: "The generated reference ID of the list.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
	}
}
