// Package ngwafsignal implements the fastly_ngwaf_signal resource.
package ngwafsignal

import (
	"regexp"

	"github.com/fastly/terraform-provider-fastly-beta/internal/resources/ngwafrule"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var signalNamePattern = regexp.MustCompile(`^[a-zA-Z0-9\- ]+$`)

// Model is the fastly_ngwaf_signal resource state.
type Model struct {
	ID          types.String `tfsdk:"id"`
	AppliesTo   types.Set    `tfsdk:"applies_to"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	ReferenceID types.String `tfsdk:"reference_id"`
}

func resourceAttributes() map[string]schema.Attribute {
	// Account rules and account signals use the same applies_to semantics.
	// Reusing the merged account-rule attribute keeps set behavior, minimum
	// size, and wildcard exclusivity identical instead of duplicating them.
	appliesTo := ngwafrule.AppliesToAttribute()
	appliesTo.Description = "The workspaces this signal applies to: a set of workspace IDs, or the single entry `*` to apply the signal to every workspace in the account. The two forms are alternatives - the wildcard cannot be combined with named workspace IDs."

	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The signal identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"applies_to": appliesTo,
		"name": schema.StringAttribute{
			Required:    true,
			Description: "The name of the signal. Must be between 3 and 128 characters and contain only letters, numbers, spaces, and hyphens. Changing this attribute will delete and recreate the signal.",
			Validators: []validator.String{
				stringvalidator.LengthBetween(3, 128),
				stringvalidator.RegexMatches(signalNamePattern, "must contain only letters, numbers, spaces, and hyphens"),
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "The description of the signal. Maximum length is 140 characters.",
			Validators: []validator.String{
				stringvalidator.LengthAtMost(140),
			},
		},
		"reference_id": schema.StringAttribute{
			Computed:    true,
			Description: "The generated reference ID of the signal, for example `site.foo-signal`.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
	}
}
