package integration

import (
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	gofastly "github.com/fastly/go-fastly/v17/fastly"
)

// go-fastly doesn't export constants for these types, so they're defined here.
const (
	typeMailingList    = "mailinglist"
	typeMicrosoftTeams = "microsoftteams"
	typeNewRelic       = "newrelic"
	typePagerDuty      = "pagerduty"
	typeSlack          = "slack"
	typeWebhook        = "webhook"
)

// integrationTypes is the single source of truth for valid `type` values.
var integrationTypes = []string{
	gofastly.IntegrationTypeDatadog,
	gofastly.IntegrationTypeJiraIssue,
	gofastly.IntegrationTypeJSM,
	typeMailingList,
	typeMicrosoftTeams,
	typeNewRelic,
	gofastly.IntegrationTypeOpsGenie,
	typePagerDuty,
	typeSlack,
	gofastly.IntegrationTypeSplunkOnCall,
	typeWebhook,
}

func typeDescription() string {
	quoted := make([]string, len(integrationTypes))
	for i, t := range integrationTypes {
		quoted[i] = fmt.Sprintf("`%s`", t)
	}
	return fmt.Sprintf("Type of the integration. One of: %s.", strings.Join(quoted, ", "))
}

type Model struct {
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	Description    types.String `tfsdk:"description"`
	Type           types.String `tfsdk:"type"`
	Config         types.Map    `tfsdk:"config"`
	Authentication types.Map    `tfsdk:"authentication"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The alphanumeric string identifying the integration, generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: "User submitted name of the integration.",
			Validators: []validator.String{
				stringvalidator.LengthBetween(1, 50),
			},
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Description: "User submitted description of the integration.",
			Validators: []validator.String{
				stringvalidator.LengthBetween(0, 300),
			},
		},
		"type": schema.StringAttribute{
			Required:    true,
			Description: typeDescription(),
			Validators: []validator.String{
				stringvalidator.OneOf(integrationTypes...),
			},
		},
		"config": schema.MapAttribute{
			Optional:    true,
			ElementType: types.StringType,
			Description: "Non-sensitive configuration specific to the integration `type` (see documentation examples). Credentials and other secret values belong in `authentication` instead.",
		},
		"authentication": schema.MapAttribute{
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
			Description: "Sensitive configuration specific to the integration `type`, such as API keys, tokens, and webhook URLs (see documentation examples). The Fastly API never returns these values, so they are not refreshed on read or import.",
		},
	}
}
