package integration

import (
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	gofastly "github.com/fastly/go-fastly/v17/fastly"
)

// go-fastly doesn't export constants for these types, so they're defined here.
const (
	typeMailingList    = "mailinglist"
	typeMicrosoftTeams = "microsoftteams"
	typeNewRelic       = "newrelic"
	typePagerDuty      = "pagerduty"
	typeSlack          = "slack"
	typeWebhook        = "webhook"
)

// integrationTypes is the single source of truth for valid `type` values.
var integrationTypes = []string{
	gofastly.IntegrationTypeDatadog,
	gofastly.IntegrationTypeJiraIssue,
	gofastly.IntegrationTypeJSM,
	typeMailingList,
	typeMicrosoftTeams,
	typeNewRelic,
	gofastly.IntegrationTypeOpsGenie,
	typePagerDuty,
	typeSlack,
	gofastly.IntegrationTypeSplunkOnCall,
	typeWebhook,
}

func typeDescription() string {
	quoted := make([]string, len(integrationTypes))
	for i, t := range integrationTypes {
		quoted[i] = fmt.Sprintf("`%s`", t)
	}
	return fmt.Sprintf("Type of the integration. One of: %s.", strings.Join(quoted, ", "))
}

type Model struct {
	ID          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	Type        types.String `tfsdk:"type"`
	Config      types.Map    `tfsdk:"config"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The alphanumeric string identifying the integration, generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: "User submitted name of the integration.",
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Description: "User submitted description of the integration.",
		},
		"type": schema.StringAttribute{
			Required:    true,
			Description: typeDescription(),
			Validators: []validator.String{
				stringvalidator.OneOf(integrationTypes...),
			},
		},
		"config": schema.MapAttribute{
			Required:    true,
			ElementType: types.StringType,
			Sensitive:   true,
			Description: "Configuration specific to the integration `type` (see documentation examples).",
		},
	}
}
