package tlssubscription

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

const DefaultForceDestroy = false

const DefaultForceUpdate = false

type Model struct {
	ID                    types.String `tfsdk:"id"`
	CertificateAuthority  types.String `tfsdk:"certificate_authority"`
	CertificateID         types.String `tfsdk:"certificate_id"`
	CommonName            types.String `tfsdk:"common_name"`
	ConfigurationID       types.String `tfsdk:"configuration_id"`
	CreatedAt             types.String `tfsdk:"created_at"`
	Domains               types.Set    `tfsdk:"domains"`
	ForceDestroy          types.Bool   `tfsdk:"force_destroy"`
	ForceUpdate           types.Bool   `tfsdk:"force_update"`
	ManagedDNSChallenges  types.Set    `tfsdk:"managed_dns_challenges"`
	ManagedHTTPChallenges types.Set    `tfsdk:"managed_http_challenges"`
	State                 types.String `tfsdk:"state"`
	UpdatedAt             types.String `tfsdk:"updated_at"`
}

var managedDNSChallengeAttrTypes = map[string]attr.Type{
	"record_name":  types.StringType,
	"record_type":  types.StringType,
	"record_value": types.StringType,
}

var managedHTTPChallengeAttrTypes = map[string]attr.Type{
	"record_name":   types.StringType,
	"record_type":   types.StringType,
	"record_values": types.SetType{ElemType: types.StringType},
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "Alphanumeric string identifying a TLS subscription.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"certificate_authority": schema.StringAttribute{
			Required:    true,
			Description: "The entity that issues and certifies the TLS certificates for your subscription. Valid values are `lets-encrypt`, `globalsign` or `certainly`.",
			Validators: []validator.String{
				stringvalidator.OneOf("lets-encrypt", "globalsign", "certainly"),
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"certificate_id": schema.StringAttribute{
			Computed:    true,
			Description: "The certificate ID associated with the subscription.",
		},
		"common_name": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "The common name associated with the subscription generated by Fastly TLS. If you do not pass a common name on create, we will default to the first TLS domain included. If provided, the domain chosen as the common name must be included in TLS domains.",
			Validators: []validator.String{
				lowercaseString{},
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
				requiresReplaceUnlessMutableString{},
			},
		},
		"configuration_id": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Description: "The ID of the set of TLS configuration options that apply to the enabled domains on this subscription.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
				requiresReplaceUnlessMutableString{},
			},
		},
		"created_at": schema.StringAttribute{
			Computed:    true,
			Description: "Timestamp (GMT) when the subscription was created.",
		},
		"domains": schema.SetAttribute{
			Required:    true,
			ElementType: types.StringType,
			Description: "List of domains on which to enable TLS.",
			Validators: []validator.Set{
				setvalidator.SizeAtLeast(1),
				lowercaseSetElements{},
			},
			PlanModifiers: []planmodifier.Set{
				requiresReplaceUnlessMutableSet{},
			},
		},
		"force_destroy": schema.BoolAttribute{
			Optional:    true,
			Computed:    true,
			Description: "Force delete the subscription even if it has active domains. Warning: this can disable production traffic if used incorrectly. Defaults to false.",
			Default:     booldefault.StaticBool(DefaultForceDestroy),
		},
		"force_update": schema.BoolAttribute{
			Optional:    true,
			Computed:    true,
			Description: "Force update the subscription even if it has active domains. Warning: this can disable production traffic if used incorrectly.",
			Default:     booldefault.StaticBool(DefaultForceUpdate),
		},
		"managed_dns_challenges": schema.SetNestedAttribute{
			Computed:    true,
			Description: "A list of options for configuring DNS to respond to ACME DNS challenge in order to verify domain ownership.",
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"record_name": schema.StringAttribute{
						Computed:    true,
						Description: "The name of the DNS record to add. For example `_acme-challenge.example.com`.",
					},
					"record_type": schema.StringAttribute{
						Computed:    true,
						Description: "The type of DNS record to add, e.g. `A`, or `CNAME`.",
					},
					"record_value": schema.StringAttribute{
						Computed:    true,
						Description: "The value to which the DNS record should point, e.g. `xxxxx.fastly-validations.com`.",
					},
				},
			},
		},
		"managed_http_challenges": schema.SetNestedAttribute{
			Computed:    true,
			Description: "A list of options for configuring DNS to respond to ACME HTTP challenge in order to verify domain ownership. Best accessed through a `for` expression to filter the relevant record.",
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"record_name": schema.StringAttribute{
						Computed:    true,
						Description: "The name of the DNS record to add. For example `example.com`. Best accessed through a `for` expression to filter the relevant record.",
					},
					"record_type": schema.StringAttribute{
						Computed:    true,
						Description: "The type of DNS record to add, e.g. `A`, or `CNAME`.",
					},
					"record_values": schema.SetAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: "A list with the value(s) to which the DNS record should point.",
					},
				},
			},
		},
		"state": schema.StringAttribute{
			Computed:    true,
			Description: "The current state of the subscription. The list of possible states are: `pending`, `processing`, `issued`, and `renewing`.",
		},
		"updated_at": schema.StringAttribute{
			Computed:    true,
			Description: "Timestamp (GMT) when the subscription was last updated.",
		},
	}
}
