package ngwafworkspace

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

const (
	DefaultDefaultBlockingResponseCode = 406
	DefaultDefaultRedirectURL          = ""
	DefaultIPAnonymization             = ""

	// These match the defaults actually applied server-side for a workspace
	// created without an explicit attack_signal_thresholds, but the API's
	// read response reports a bare zero for a threshold that was never
	// explicitly set rather than the applied default. flattenAttackSignalThresholds
	// re-applies these same values on read/import so state reflects what the
	// workspace is really doing rather than the response's literal zero.
	DefaultAttackSignalImmediate  = false
	DefaultAttackSignalOneHour    = 100
	DefaultAttackSignalOneMinute  = 1
	DefaultAttackSignalTenMinutes = 60
)

type Model struct {
	ID                          types.String                  `tfsdk:"id"`
	Name                        types.String                  `tfsdk:"name"`
	Description                 types.String                  `tfsdk:"description"`
	Mode                        types.String                  `tfsdk:"mode"`
	IPAnonymization             types.String                  `tfsdk:"ip_anonymization"`
	ClientIPHeaders             types.List                    `tfsdk:"client_ip_headers"`
	DefaultBlockingResponseCode types.Int64                   `tfsdk:"default_blocking_response_code"`
	DefaultRedirectURL          types.String                  `tfsdk:"default_redirect_url"`
	AttackSignalThresholds      []AttackSignalThresholdsModel `tfsdk:"attack_signal_thresholds"`
}

type AttackSignalThresholdsModel struct {
	Immediate  types.Bool  `tfsdk:"immediate"`
	OneHour    types.Int64 `tfsdk:"one_hour"`
	OneMinute  types.Int64 `tfsdk:"one_minute"`
	TenMinutes types.Int64 `tfsdk:"ten_minutes"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The Next-Gen WAF workspace identifier (UUID) generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: "The display name of the workspace. Must be between 3 and 100 characters.",
			Validators: []validator.String{
				stringvalidator.LengthBetween(3, 100),
			},
		},
		"description": schema.StringAttribute{
			Required:    true,
			Description: "The description of the workspace. Must be at most 500 characters.",
			Validators: []validator.String{
				stringvalidator.LengthAtMost(500),
			},
		},
		"mode": schema.StringAttribute{
			Required:    true,
			Description: "The operation mode of the workspace. Valid values are `off`, `log`, and `block`.",
			Validators: []validator.String{
				stringvalidator.OneOf("off", "log", "block"),
			},
		},
		"ip_anonymization": schema.StringAttribute{
			Optional:    true,
			Description: "Anonymizes IP addresses according to the selected option. The only accepted value is `hashed`. When omitted, IP addresses are not anonymized.",
			Validators: []validator.String{
				stringvalidator.OneOf("hashed"),
			},
		},
		"client_ip_headers": schema.ListAttribute{
			ElementType: types.StringType,
			Optional:    true,
			Description: "The request headers containing the client IP address. Maximum of 10 header names.",
			Validators: []validator.List{
				listvalidator.SizeAtMost(10),
				listvalidator.ValueStringsAre(stringvalidator.LengthAtLeast(1)),
			},
		},
		"default_blocking_response_code": schema.Int64Attribute{
			Optional:    true,
			Computed:    true,
			Default:     int64default.StaticInt64(DefaultDefaultBlockingResponseCode),
			Description: "The status code returned when a request is blocked. Applied at the workspace level, but can be overridden by individual rules. Accepted values are `301`, `302`, or any value between `400` and `599`. Defaults to `406`.",
			Validators: []validator.Int64{
				blockingResponseCodeValidator{},
			},
		},
		"default_redirect_url": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString(DefaultDefaultRedirectURL),
			Description: "The URL used when `default_blocking_response_code` is `301` or `302`.",
		},
	}
}

// AttackSignalThresholdsBlock is required and constrained to exactly one
// entry: attack signal thresholds are a singleton set of workspace
// parameters, not a repeatable collection, but the schema exposes it as a
// block (rather than a single nested attribute) to match the HCL shape of
// the resource this replaces.
func AttackSignalThresholdsBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Attack signal threshold parameters used for system site alerts. Each threshold is the number of attack signals per IP address that must be detected during the interval before the associated IP address is flagged. Exactly one block is required.",
		Validators: []validator.List{
			listvalidator.SizeBetween(1, 1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"immediate": schema.BoolAttribute{
					Optional:    true,
					Computed:    true,
					Default:     booldefault.StaticBool(DefaultAttackSignalImmediate),
					Description: "Ignore thresholds and block immediately when at least one attack signal is detected. Defaults to `false`.",
				},
				"one_hour": schema.Int64Attribute{
					Optional:    true,
					Computed:    true,
					Default:     int64default.StaticInt64(DefaultAttackSignalOneHour),
					Description: "The one-hour interval threshold. Minimum `1`, maximum `10000`. Defaults to `100`.",
					Validators: []validator.Int64{
						int64validator.Between(1, 10000),
					},
				},
				"one_minute": schema.Int64Attribute{
					Optional:    true,
					Computed:    true,
					Default:     int64default.StaticInt64(DefaultAttackSignalOneMinute),
					Description: "The one-minute interval threshold. Minimum `1`, maximum `10000`. Defaults to `1`.",
					Validators: []validator.Int64{
						int64validator.Between(1, 10000),
					},
				},
				"ten_minutes": schema.Int64Attribute{
					Optional:    true,
					Computed:    true,
					Default:     int64default.StaticInt64(DefaultAttackSignalTenMinutes),
					Description: "The ten-minute interval threshold. Minimum `1`, maximum `10000`. Defaults to `60`.",
					Validators: []validator.Int64{
						int64validator.Between(1, 10000),
					},
				},
			},
		},
	}
}
