package ngwafthresholds

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// DefaultDuration is the value the API assigns to duration when it's
// omitted from the request body.
const DefaultDuration = 86400

// DefaultInterval is the value the API assigns to interval when it's
// omitted from the request body.
const DefaultInterval = 3600

// DefaultLimit is the value the API assigns to limit when it's omitted
// from the request body.
const DefaultLimit = 10

type Model struct {
	ID          types.String `tfsdk:"id"`
	WorkspaceID types.String `tfsdk:"workspace_id"`
	Action      types.String `tfsdk:"action"`
	DontNotify  types.Bool   `tfsdk:"dont_notify"`
	Duration    types.Int64  `tfsdk:"duration"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	Interval    types.Int64  `tfsdk:"interval"`
	Limit       types.Int64  `tfsdk:"limit"`
	Name        types.String `tfsdk:"name"`
	Signal      types.String `tfsdk:"signal"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The Next-Gen WAF threshold identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"workspace_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the workspace this threshold belongs to.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"action": schema.StringAttribute{
			Required:    true,
			Description: "Action to take when threshold is exceeded. One of `block`, `block_immediately`, or `log`.",
			Validators: []validator.String{
				stringvalidator.OneOf("block", "block_immediately", "log"),
			},
		},
		"dont_notify": schema.BoolAttribute{
			Required:    true,
			Description: "Whether to silence notifications when action is taken.",
		},
		"duration": schema.Int64Attribute{
			Optional:    true,
			Computed:    true,
			Default:     int64default.StaticInt64(DefaultDuration),
			Description: "Duration the action is in place, in seconds. Minimum `1` and maximum `31556900`. Defaults to `86400` (1 day).",
			Validators: []validator.Int64{
				int64validator.Between(1, 31556900),
			},
		},
		"enabled": schema.BoolAttribute{
			Required:    true,
			Description: "Whether this threshold is active.",
		},
		"interval": schema.Int64Attribute{
			Optional:    true,
			Computed:    true,
			Default:     int64default.StaticInt64(DefaultInterval),
			Description: "Threshold interval in seconds. One of `60`, `600`, or `3600`. Defaults to `3600` (1 hour).",
			Validators: []validator.Int64{
				int64validator.OneOf(60, 600, 3600),
			},
		},
		"limit": schema.Int64Attribute{
			Optional:    true,
			Computed:    true,
			Default:     int64default.StaticInt64(DefaultLimit),
			Description: "Threshold limit. Minimum `1` and maximum `100000`. Defaults to `10`.",
			Validators: []validator.Int64{
				int64validator.Between(1, 100000),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: "The name of the threshold. Must be between 3 and 50 characters.",
			Validators: []validator.String{
				stringvalidator.LengthBetween(3, 50),
			},
		},
		"signal": schema.StringAttribute{
			Required:    true,
			Description: "The name of the signal this threshold is acting on.",
		},
	}
}
