package ngwafalertintegration

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

func Attributes(def Definition) map[string]schema.Attribute {
	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The workspace alert integration identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"workspace_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the workspace that owns the alert integration.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: fmt.Sprintf("The description of the %s alert integration. Changing this attribute will delete and recreate the alert integration.", def.Type),
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
	}

	for _, attr := range def.ConfigAttrs {
		validators := []validator.String{}
		switch attr.Name {
		case "site":
			validators = append(validators, stringvalidator.OneOf("us1", "us3", "us5", "eu1"))
		case "address":
			validators = append(validators, stringvalidator.LengthBetween(1, 320))
		case "host", "username", "project", "key", "webhook":
			validators = append(validators, stringvalidator.LengthAtLeast(1))
		}

		attribute := schema.StringAttribute{
			Sensitive:   attr.Sensitive,
			Description: attr.Description,
			Validators:  validators,
		}
		if attr.Optional {
			attribute.Optional = true
			attribute.Computed = true
			if attr.Default != "" {
				attribute.Default = stringdefault.StaticString(attr.Default)
			}
		} else {
			attribute.Required = true
		}

		attrs[attr.Name] = attribute
	}

	return attrs
}
