package tlssubscription

import (
	"context"
	"slices"
	"time"

	fastlyclient "github.com/fastly/terraform-provider-fastly-beta/internal/client"
	"github.com/fastly/terraform-provider-fastly-beta/internal/service"

	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/fastly/go-fastly/v17/fastly"
)

var _ datasource.DataSource = &DataSource{}

type DataSource struct {
	client *fastly.Client
}

type DataSourceModel struct {
	ID                   types.String `tfsdk:"id"`
	CertificateAuthority types.String `tfsdk:"certificate_authority"`
	CertificateIDs       types.Set    `tfsdk:"certificate_ids"`
	CommonName           types.String `tfsdk:"common_name"`
	ConfigurationID      types.String `tfsdk:"configuration_id"`
	CreatedAt            types.String `tfsdk:"created_at"`
	Domains              types.Set    `tfsdk:"domains"`
	State                types.String `tfsdk:"state"`
	UpdatedAt            types.String `tfsdk:"updated_at"`
}

func NewDataSource() datasource.DataSource {
	return &DataSource{}
}

func (d *DataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tls_subscription"
}

func (d *DataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to get the ID of a TLS subscription, or to look up the certificate, configuration, or domains of an existing subscription.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "ID of TLS subscription. Conflicts with all the other filters.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(
						path.MatchRoot("configuration_id"),
						path.MatchRoot("domains"),
						path.MatchRoot("certificate_authority"),
					),
				},
			},
			"certificate_authority": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "The entity that issues and certifies the TLS certificates for the subscription.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("id")),
				},
			},
			"certificate_ids": schema.SetAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: "List of certificate IDs associated with the Subscription.",
			},
			"common_name": schema.StringAttribute{
				Computed:    true,
				Description: "The common name associated with the subscription generated by Fastly TLS.",
			},
			"configuration_id": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "ID of TLS configuration used to terminate TLS traffic.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("id")),
				},
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Timestamp (GMT) when subscription was created.",
			},
			"domains": schema.SetAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Description: "List of domains on which to enable TLS.",
				Validators: []validator.Set{
					setvalidator.ConflictsWith(path.MatchRoot("id")),
				},
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: "The current state of the subscription. The list of possible states are: `pending`, `processing`, `issued`, and `renewing`.",
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: "Timestamp (GMT) when subscription was last updated.",
			},
		},
	}
}

func (d *DataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	data, diags := fastlyclient.FromProviderData(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || data == nil {
		return
	}
	d.client = data.Client
}

func (d *DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config DataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var subscription *fastly.TLSSubscription

	if id := service.StringValue(config.ID); id != "" {
		tflog.Debug(ctx, "Reading Fastly TLS subscription", map[string]any{"id": id})

		found, err := d.client.GetTLSSubscription(ctx, &fastly.GetTLSSubscriptionInput{ID: id})
		if err != nil {
			resp.Diagnostics.AddError("Error reading TLS subscription", err.Error())
			return
		}
		subscription = found
	} else {
		tflog.Debug(ctx, "Listing Fastly TLS subscriptions to find a match")

		subscriptions, err := listSubscriptions(ctx, d.client)
		if err != nil {
			resp.Diagnostics.AddError("Error listing TLS subscriptions", err.Error())
			return
		}

		matches, diags := filterSubscriptions(ctx, subscriptions, config)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}

		switch len(matches) {
		case 0:
			resp.Diagnostics.AddError("No matching TLS subscription found", "your query returned no results. Please change your search criteria and try again")
			return
		case 1:
			subscription = matches[0]
		default:
			resp.Diagnostics.AddError("Multiple matching TLS subscriptions found", "your query returned more than one result. Please change to a more specific search criteria")
			return
		}
	}

	newState, diags := flattenToModel(subscription)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &newState)...)
}

func listSubscriptions(ctx context.Context, client *fastly.Client) ([]*fastly.TLSSubscription, error) {
	var subscriptions []*fastly.TLSSubscription
	pageNumber := 1
	for {
		list, err := client.ListTLSSubscriptions(ctx, &fastly.ListTLSSubscriptionsInput{
			PageNumber: pageNumber,
			PageSize:   10,
		})
		if err != nil {
			return nil, err
		}
		if len(list) == 0 {
			break
		}
		pageNumber++
		subscriptions = append(subscriptions, list...)
	}
	return subscriptions, nil
}

func filterSubscriptions(ctx context.Context, subscriptions []*fastly.TLSSubscription, config DataSourceModel) ([]*fastly.TLSSubscription, diag.Diagnostics) {
	var diags diag.Diagnostics

	configurationID := service.StringValue(config.ConfigurationID)
	certificateAuthority := service.StringValue(config.CertificateAuthority)

	var domainsToMatch []string
	if !config.Domains.IsNull() && !config.Domains.IsUnknown() {
		diags.Append(config.Domains.ElementsAs(ctx, &domainsToMatch, false)...)
	}
	if diags.HasError() {
		return nil, diags
	}

	var matches []*fastly.TLSSubscription
	for _, s := range subscriptions {
		if configurationID != "" && (s.Configuration == nil || s.Configuration.ID != configurationID) {
			continue
		}
		if certificateAuthority != "" && s.CertificateAuthority != certificateAuthority {
			continue
		}
		if len(domainsToMatch) > 0 {
			var foundDomains []string
			for _, d := range s.Domains {
				foundDomains = append(foundDomains, d.ID)
			}
			if !containsAll(foundDomains, domainsToMatch) {
				continue
			}
		}
		matches = append(matches, s)
	}

	return matches, diags
}

func containsAll(haystack, needles []string) bool {
	for _, needle := range needles {
		if !slices.Contains(haystack, needle) {
			return false
		}
	}
	return true
}

func flattenToModel(subscription *fastly.TLSSubscription) (DataSourceModel, diag.Diagnostics) {
	var diags diag.Diagnostics

	certIDs := make([]string, 0, len(subscription.Certificates))
	for _, cert := range subscription.Certificates {
		if cert != nil {
			certIDs = append(certIDs, cert.ID)
		}
	}
	certIDsSet, certDiags := types.SetValueFrom(context.Background(), types.StringType, certIDs)
	diags.Append(certDiags...)

	domains := make([]string, 0, len(subscription.Domains))
	for _, d := range subscription.Domains {
		if d != nil {
			domains = append(domains, d.ID)
		}
	}
	domainsSet, domainsDiags := types.SetValueFrom(context.Background(), types.StringType, domains)
	diags.Append(domainsDiags...)

	if diags.HasError() {
		return DataSourceModel{}, diags
	}

	commonName := ""
	if subscription.CommonName != nil {
		commonName = subscription.CommonName.ID
	}
	configurationID := ""
	if subscription.Configuration != nil {
		configurationID = subscription.Configuration.ID
	}

	m := DataSourceModel{
		ID:                   types.StringValue(subscription.ID),
		CertificateAuthority: types.StringValue(subscription.CertificateAuthority),
		CertificateIDs:       certIDsSet,
		CommonName:           types.StringValue(commonName),
		ConfigurationID:      types.StringValue(configurationID),
		Domains:              domainsSet,
		State:                types.StringValue(subscription.State),
		CreatedAt:            types.StringNull(),
		UpdatedAt:            types.StringNull(),
	}
	if subscription.CreatedAt != nil {
		m.CreatedAt = types.StringValue(subscription.CreatedAt.Format(time.RFC3339))
	}
	if subscription.UpdatedAt != nil {
		m.UpdatedAt = types.StringValue(subscription.UpdatedAt.Format(time.RFC3339))
	}

	return m, diags
}
