package ngwafworkspaceredaction

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var redactionTypes = []string{"request_parameter", "request_header", "response_header"}

type Model struct {
	ID          types.String `tfsdk:"id"`
	WorkspaceID types.String `tfsdk:"workspace_id"`
	Field       types.String `tfsdk:"field"`
	Type        types.String `tfsdk:"type"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "A base62-encoded representation of a UUID used to uniquely identify a redaction generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"workspace_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the workspace that owns the redaction.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"field": schema.StringAttribute{
			Required:    true,
			Description: "The name of the field that should be redacted.",
			Validators: []validator.String{
				stringvalidator.LengthAtLeast(1),
			},
		},
		"type": schema.StringAttribute{
			Required:    true,
			Description: "The type of field that is being redacted. Accepted values are `request_parameter`, `request_header`, and `response_header`.",
			Validators: []validator.String{
				stringvalidator.OneOf(redactionTypes...),
			},
		},
	}
}
