package customdashboard

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

const (
	DefaultSpan                int64  = 4
	DefaultVisualizationFormat string = "number"
)

type Model struct {
	ID            types.String         `tfsdk:"id"`
	Name          types.String         `tfsdk:"name"`
	Description   types.String         `tfsdk:"description"`
	DashboardItem []DashboardItemModel `tfsdk:"dashboard_item"`
}

type DashboardItemModel struct {
	Key           types.String         `tfsdk:"key"`
	ID            types.String         `tfsdk:"id"`
	Title         types.String         `tfsdk:"title"`
	Subtitle      types.String         `tfsdk:"subtitle"`
	Span          types.Int64          `tfsdk:"span"`
	DataSource    []DataSourceModel    `tfsdk:"data_source"`
	Visualization []VisualizationModel `tfsdk:"visualization"`
}

type DataSourceModel struct {
	Type   types.String            `tfsdk:"type"`
	Config []DataSourceConfigModel `tfsdk:"config"`
}

type DataSourceConfigModel struct {
	Metrics types.List `tfsdk:"metrics"`
}

type VisualizationModel struct {
	Type   types.String               `tfsdk:"type"`
	Config []VisualizationConfigModel `tfsdk:"config"`
}

type VisualizationConfigModel struct {
	CalculationMethod types.String `tfsdk:"calculation_method"`
	Format            types.String `tfsdk:"format"`
	PlotType          types.String `tfsdk:"plot_type"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "Dashboard identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: "A human-readable name for the custom dashboard.",
			Validators: []validator.String{
				stringvalidator.LengthAtLeast(1),
			},
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Description: "A short description of the dashboard.",
		},
	}
}

func DashboardItemsBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Dashboard items displayed in this custom dashboard. Items are ordered. `key` is Terraform-owned identity; `id` is generated by Fastly.",
		Validators: []validator.List{
			listvalidator.SizeAtMost(100),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"key": schema.StringAttribute{
					Required:    true,
					Description: "Stable Terraform identity for this dashboard item. Must be unique within the dashboard. Changing it causes the item to be treated as a new item.",
					Validators: []validator.String{
						stringvalidator.LengthAtLeast(1),
					},
				},
				"id": schema.StringAttribute{
					Computed:    true,
					Description: "Dashboard item identifier generated by Fastly. This value is read-only and must not be configured.",
				},
				"title": schema.StringAttribute{
					Required:    true,
					Description: "A human-readable title for the dashboard item.",
					Validators: []validator.String{
						stringvalidator.LengthAtLeast(1),
					},
				},
				"subtitle": schema.StringAttribute{
					Required:    true,
					Description: "A human-readable subtitle for the dashboard item. Often a description of the visualization.",
				},
				"span": schema.Int64Attribute{
					Optional:    true,
					Computed:    true,
					Default:     int64default.StaticInt64(DefaultSpan),
					Description: "Number of columns the item spans on the dashboard's 12-column grid. Defaults to 4.",
					Validators: []validator.Int64{
						int64validator.Between(1, 12),
					},
				},
			},
			Blocks: map[string]schema.Block{
				"data_source":   DataSourceBlock(),
				"visualization": VisualizationBlock(),
			},
		},
	}
}

func DataSourceBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Data source displayed by this dashboard item.",
		Validators: []validator.List{
			listvalidator.SizeBetween(1, 1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"type": schema.StringAttribute{
					Required:    true,
					Description: "The source of the data to display.",
					Validators: []validator.String{
						stringvalidator.OneOf("stats.edge", "stats.domain", "stats.origin"),
					},
				},
			},
			Blocks: map[string]schema.Block{
				"config": DataSourceConfigBlock(),
			},
		},
	}
}

func DataSourceConfigBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Configuration options for the selected data source.",
		Validators: []validator.List{
			listvalidator.SizeBetween(1, 1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"metrics": schema.ListAttribute{
					ElementType: types.StringType,
					Required:    true,
					Description: "Metrics to visualize. Valid metric names depend on the selected data source.",
					Validators: []validator.List{
						listvalidator.SizeAtLeast(1),
						listvalidator.ValueStringsAre(stringvalidator.LengthAtLeast(1)),
					},
				},
			},
		},
	}
}

func VisualizationBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Visualization used to display the dashboard item.",
		Validators: []validator.List{
			listvalidator.SizeBetween(1, 1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"type": schema.StringAttribute{
					Required:    true,
					Description: "The visualization type.",
					Validators: []validator.String{
						stringvalidator.OneOf("chart"),
					},
				},
			},
			Blocks: map[string]schema.Block{
				"config": VisualizationConfigBlock(),
			},
		},
	}
}

func VisualizationConfigBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Configuration options for the chart visualization.",
		Validators: []validator.List{
			listvalidator.SizeBetween(1, 1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"calculation_method": schema.StringAttribute{
					Optional:    true,
                    Description: "The aggregation function to apply to the dataset. One of: `avg`, `sum`, `min`, `max`, `latest`, `p95`.",
					Validators: []validator.String{
						stringvalidator.OneOf("avg", "sum", "min", "max", "latest", "p95"),
					},
				},
				"format": schema.StringAttribute{
					Optional:    true,
					Computed:    true,
					Default:     stringdefault.StaticString(DefaultVisualizationFormat),
					Description: "Units used to format the data. Defaults to `number`.",
					Validators: []validator.String{
						stringvalidator.OneOf("number", "bytes", "percent", "requests", "responses", "seconds", "milliseconds", "ratio", "bitrate"),
					},
				},
				"plot_type": schema.StringAttribute{
					Required:    true,
                    Description: "The type of chart to display. One of: `line`, `bar`, `single-metric`, `donut`.",
					Validators: []validator.String{
						stringvalidator.OneOf("line", "bar", "single-metric", "donut"),
					},
				},
			},
		},
	}
}
