package ngwafworkspacevirtualpatch

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Model struct {
	ID             types.String `tfsdk:"id"`
	WorkspaceID    types.String `tfsdk:"workspace_id"`
	VirtualPatchID types.String `tfsdk:"virtual_patch_id"`
	Mode           types.String `tfsdk:"mode"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	Description    types.String `tfsdk:"description"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The Next-Gen WAF virtual patch identifier generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"workspace_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the workspace this virtual patch belongs to.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
			Validators: []validator.String{
				stringvalidator.LengthAtLeast(1),
			},
		},
		"virtual_patch_id": schema.StringAttribute{
			Required:    true,
			Description: "The ID of the existing virtual patch to configure. Virtual patches are created by Fastly and cannot be created by this resource. Changing this attribute will delete and recreate the Terraform resource.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
			Validators: []validator.String{
				stringvalidator.LengthAtLeast(1),
			},
		},
		"mode": schema.StringAttribute{
			Required:    true,
			Description: "Action to take when a signal for virtual patch is detected. One of `block` or `log`.",
			Validators: []validator.String{
				stringvalidator.OneOf("block", "log"),
			},
		},
		"enabled": schema.BoolAttribute{
			Required:    true,
			Description: "Control for enabling and disabling a virtual patch.",
		},
		"description": schema.StringAttribute{
			Computed:    true,
			Description: "Description of the virtual patch.",
		},
	}
}
