package alert

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/float64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

const (
	managedByTerraform = "Managed by Terraform"

	badAlertSourceServiceIDConfig = "empty `service_id` is only supported for `stats` as a source"
)

var (
	evaluationStrategyTypes   = []string{"above_threshold", "all_above_threshold", "below_threshold", "percent_absolute", "percent_decrease", "percent_increase"}
	evaluationStrategyPeriods = []string{"2m", "3m", "5m", "15m", "30m"}
	alertSources              = []string{"domains", "origins", "stats"}
)

type Model struct {
	ID                 types.String              `tfsdk:"id"`
	Name               types.String              `tfsdk:"name"`
	Description        types.String              `tfsdk:"description"`
	ServiceID          types.String              `tfsdk:"service_id"`
	Source             types.String              `tfsdk:"source"`
	Metric             types.String              `tfsdk:"metric"`
	IntegrationIDs     types.Set                 `tfsdk:"integration_ids"`
	Dimensions         []DimensionsModel         `tfsdk:"dimensions"`
	EvaluationStrategy []EvaluationStrategyModel `tfsdk:"evaluation_strategy"`
}

type DimensionsModel struct {
	Domains types.Set `tfsdk:"domains"`
	Origins types.Set `tfsdk:"origins"`
}

type EvaluationStrategyModel struct {
	Type        types.String  `tfsdk:"type"`
	Period      types.String  `tfsdk:"period"`
	Threshold   types.Float64 `tfsdk:"threshold"`
	IgnoreBelow types.Float64 `tfsdk:"ignore_below"`
}

func ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "The alphanumeric string identifying the alert definition, generated by Fastly.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"name": schema.StringAttribute{
			Required:    true,
			Description: "The name of the alert definition.",
			Validators: []validator.String{
				stringvalidator.LengthAtMost(255),
			},
		},
		"description": schema.StringAttribute{
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "Additional text that is included in the alert notification.",
			Validators: []validator.String{
				stringvalidator.LengthAtMost(4096),
			},
		},
		"service_id": schema.StringAttribute{
			Optional:    true,
			Description: "The service which the alert monitors. Optional when using `stats` as the `source`.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"source": schema.StringAttribute{
			Required:    true,
			Description: "The service on which the definition will alert on. One of: `domains`, `origins`, `stats`.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
			Validators: []validator.String{
				stringvalidator.OneOf(alertSources...),
			},
		},
		"metric": schema.StringAttribute{
			Required:    true,
			Description: "The metric name to alert on for a specific source: [domains](https://developer.fastly.com/reference/api/metrics-stats/domain-inspector/historical), [origins](https://developer.fastly.com/reference/api/metrics-stats/origin-inspector/historical), or [stats](https://developer.fastly.com/reference/api/metrics-stats/historical-stats).",
		},
		"integration_ids": schema.SetAttribute{
			ElementType: types.StringType,
			Optional:    true,
			Computed:    true,
			Description: "List of integrations used to notify when alert fires.",
			Validators: []validator.Set{
				setvalidator.SizeAtMost(10),
			},
		},
	}
}

// A singleton, exposed as a list block rather than a single nested attribute.
func DimensionsBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "More filters depending on the source type.",
		Validators: []validator.List{
			listvalidator.SizeAtMost(1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"domains": schema.SetAttribute{
					ElementType: types.StringType,
					Optional:    true,
					Description: "Names of a subset of domains that the alert monitors.",
				},
				"origins": schema.SetAttribute{
					ElementType: types.StringType,
					Optional:    true,
					Description: "Addresses of a subset of backends that the alert monitors.",
				},
			},
		},
	}
}

func EvaluationStrategyBlock() schema.ListNestedBlock {
	return schema.ListNestedBlock{
		Description: "Criteria on how to alert. Exactly one block is required.",
		Validators: []validator.List{
			listvalidator.SizeBetween(1, 1),
		},
		NestedObject: schema.NestedBlockObject{
			Attributes: map[string]schema.Attribute{
				"type": schema.StringAttribute{
					Required:    true,
					Description: "Type of strategy to use to evaluate. One of: `above_threshold`, `all_above_threshold`, `below_threshold`, `percent_absolute`, `percent_decrease`, `percent_increase`.",
					Validators: []validator.String{
						stringvalidator.OneOf(evaluationStrategyTypes...),
					},
				},
				"period": schema.StringAttribute{
					Required:    true,
					Description: "The length of time to evaluate whether the conditions have been met. The data is polled every minute. One of: `2m`, `3m`, `5m`, `15m`, `30m`.",
					Validators: []validator.String{
						stringvalidator.OneOf(evaluationStrategyPeriods...),
					},
				},
				"threshold": schema.Float64Attribute{
					Required:    true,
					Description: "Threshold used to alert.",
					Validators: []validator.Float64{
						float64validator.AtLeast(0),
					},
				},
				"ignore_below": schema.Float64Attribute{
					Optional:    true,
					Description: "Threshold for the denominator value used in evaluations that calculate a rate or ratio. Usually used to filter out noise.",
					Validators: []validator.Float64{
						float64validator.AtLeast(0.00001),
					},
				},
			},
		},
	}
}
