name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test (${{ matrix.platform }})
    strategy:
      matrix:
        go-version: [1.26.x]
        platform: [forge-amd64-small]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: make test-unit

  docs:
    runs-on: forge-amd64-small
    if: "!contains(github.event.pull_request.labels.*.name, 'Skip-Docs')"
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.x

      - name: Generate Docs
        run: make generate-docs

      - name: Validate Docs
        run: make validate-docs

      - name: Check docs diff
        run: git diff --exit-code --ignore-all-space ./docs/
